"""Git hooks integration for automatic event logging."""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Optional

from .models import IDESource, MemoryEvent
from .storage import StorageEngine
from .sync import SyncEngine


class GitHooksManager:
    """Manager for Git hooks integration."""

    def __init__(self, project_dir: Path, storage: StorageEngine, sync_engine: SyncEngine):
        """Initialize Git hooks manager.

        Args:
            project_dir: Project root directory
            storage: Storage engine instance
            sync_engine: Sync engine instance
        """
        self.project_dir = Path(project_dir).resolve()
        self.storage = storage
        self.sync_engine = sync_engine
        self.git_dir = self.project_dir / ".git"

    def install_hooks(self) -> bool:
        """Install post-commit hook.

        Returns:
            True if installed successfully
        """
        if not self.git_dir.exists():
            return False

        hooks_dir = self.git_dir / "hooks"
        hooks_dir.mkdir(exist_ok=True)

        post_commit_hook = hooks_dir / "post-commit"

        # Generate hook script
        hook_script = f"""#!/bin/sh
# Memory Share post-commit hook
# Auto-generated by memory-share init

cd "{self.project_dir}"
python -m memory_share.git_hooks post_commit "$@"
"""

        post_commit_hook.write_text(hook_script, encoding="utf-8")
        post_commit_hook.chmod(0o755)

        return True

    def handle_post_commit(self) -> None:
        """Handle post-commit hook: log commit as event."""
        try:
            # Get last commit message
            result = subprocess.run(
                ["git", "log", "-1", "--pretty=%B"],
                cwd=self.project_dir,
                capture_output=True,
                text=True,
                timeout=5,
            )
            commit_message = result.stdout.strip() if result.returncode == 0 else ""

            # Get changed files
            result = subprocess.run(
                ["git", "diff-tree", "--no-commit-id", "--name-only", "-r", "HEAD"],
                cwd=self.project_dir,
                capture_output=True,
                text=True,
                timeout=5,
            )
            changed_files = (
                result.stdout.strip().split("\n") if result.returncode == 0 else []
            )
            changed_files = [f for f in changed_files if f]

            # Create event
            summary = f"Git commit: {commit_message[:100]}"
            if len(commit_message) > 100:
                summary += "..."

            # Register system session if needed
            session_id = self.sync_engine.register_session(IDESource.SYSTEM)

            # Push as event
            self.sync_engine.push_summary(
                session_id=session_id,
                summary=summary,
                content=commit_message,
                tags=["git", "commit"],
                related_files=changed_files[:10],  # Limit files
            )
        except Exception:
            pass  # Fail silently in hook


def main():
    """CLI entry point for git hooks."""
    import sys

    if len(sys.argv) < 2:
        return

    command = sys.argv[1]
    project_dir = Path.cwd()

    storage = StorageEngine(project_dir)
    storage.initialize()

    from .consistency import ConsistencyLayer
    from .sync import SyncEngine

    consistency = ConsistencyLayer(storage)
    sync_engine = SyncEngine(storage, consistency)

    manager = GitHooksManager(project_dir, storage, sync_engine)

    if command == "post_commit":
        manager.handle_post_commit()


if __name__ == "__main__":
    main()
